In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import random
from sympy import symbols, latex

#### Q1 How many multiplications and additions do you need to perform a matrix multiplication between a (n, k) and (k, m) matrix? Explain.

**Ans** : We require n.m.k multiplication and n.m.(k-1) addition.
      So, The number of elements in the resultant matrix is n.m
      and to get each element we require k multiplication followed by k-1 addition.
      Hence a total of n.m.k multiplication and n.m.(k-1) addition is required.


#### Q2 Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?

In [2]:
# First I am creating a random matrix using list of lists of sizes (200x300) and (300*400)

a = [random.sample(range(1000), 300)]*200
b = [random.sample(range(1000), 400)]*300

# Function to multiply two matrix using list of lists.

def matrix_multiply(a, b):
    result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]
    
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
                
    return result


# Second I have created a np 2d array using list.

a_np = np.array(a)
b_np = np.array(b)


In [3]:
import time

# Measure time for list of lists
start_time = time.time()
result_python = matrix_multiply(a,b)
end_time = time.time()
print((end_time - start_time)*1000)

# Measure time for NumPy
start_time = time.time()
result_numpy = np.dot(a_np,b_np)
end_time = time.time()
print((end_time - start_time)*1000)

12300.540208816528
41.76163673400879


<br>From the above result we can clearly see the time taken by the Matrix multiplication using list of list is very much higher than that of numpy

The reason behind this is that NumPy is a highly optimized numerical computing library in Python, and it is designed to perform operations on arrays with a high level of efficiency. Below are the advantages that numpy array have over list.

1. NumPy arrays are homogeneous, meaning all elements in the array have the same data type. This allows for more efficient storage and operations. In contrast, lists in Python can hold elements of different data types, which introduces overhead.
2. NumPy arrays have a contiguous memory layout, which allows for more efficient memory access patterns. Lists of lists in Python may not have contiguous memory, leading to less efficient memory access.


#### Q3 Finding the highest element in a list requires one pass of the array. Finding the second highest element requires 2 passes of the the array. Using this method, what is the time complexity of finding the median of the array? Can you suggest a better method? Can you implement both these methods in Python and compare against numpy.median routine in terms of time?

**Ans** Using first method it will take $n/2$ iteration and each iteration will take n passes so a total of $n^2/2$ time which is equivalent to $O(n^2)$.
There is another better approach than this it will take $O(nlogn)$ time. And its preety simple. 
We will first sort the array and return the middle element.
Below are the code for all methods.

In [4]:
# First we are creating an Random array of Integers

a = np.random.randint(0,100,10001)

In [5]:
# Creating Function For linear search

def Median_Linear(arr):
    n = int(len(arr)/2)
    for i in range(n+1):
        maxi=0
        max=0
        for j in range(len(arr)-i):
            if arr[j]>max:
                max=arr[j]
                maxi=j
        arr[maxi]=arr[len(arr)-i-1]
        arr[len(arr)-i-1]=max
    return arr[n]
            

In [6]:
# Creating Function For Sorting method

def Median_sort(arr):
    n= int(len(arr)/2)
    arr.sort()
    return arr[n]

In [7]:
# Comparing the time between all methods

# Linear Method
start= time.time()
p=Median_Linear(a.copy())
end = time.time()
print("Median is: " , p)
print("Time taken: ", end-start)

# Sorting Method
start= time.time()
q=Median_sort(a.copy())
end = time.time()
print("Median is: " , q)
print("Time taken: ", end-start)

# Inbuilt numpy
start= time.time()
r=np.median(a)
end = time.time()
print("Median is: " , r)
print("Time taken: ", end-start)


Median is:  51
Time taken:  14.73305630683899
Median is:  51
Time taken:  0.0
Median is:  51.0
Time taken:  0.014020442962646484


Its can be seen from the results that the time taken by the Linear method is much much higher than the sorting and inbuilt numpy methods

#### Q4 What is the gradient of the following function with respect to x and y?    

$x^2y + y^3 sin(x) $  


**Ans**
Gradient of the above function is the partial derivative with respect to x and y. <br>
Hence,  

With Respect to x: 
    $2xy + y^3 cos(x) $  <br>
    
With Respect to y:
    $x^2 + 3y^2sin(x)$

#### Q5 Use JAX to confirm the gradient evaluated by your method matches the analytical solution corresponding to a few random values of x and y

In [8]:
import jax
import jax.numpy as jnp

In [9]:
def With_x(x,y):
    return 2*x*y + y**3 * jnp.cos(x)

def With_y(x,y):
    return x**2 + 3* y**2 * jnp.sin(x)

def Original(x,y):
    return x**2 * y + y**3 * jnp.sin(x)


Grad_Original = jax.grad(Original, argnums=(0, 1))

x=4.0
y=10.0

x_val= Grad_Original(x,y)[0]
y_val = Grad_Original(x,y)[1]

x1= With_x(x,y)
y1= With_y(x,y)
print(f"The Gradient of Original Function using JAX at x={x} is: {x_val} and at y={y} is: {y_val}")
print("\n")
print("The Gradient without using JAX at x=4.0 is: ",x1, "and at y=10.0 is: ", y1 )
print("\n")

The Gradient of Original Function using JAX at x=4.0 is: -573.6436157226562 and at y=10.0 is: -211.04075622558594


The Gradient without using JAX at x=4.0 is:  -573.6436 and at y=10.0 is:  -211.04076




Hence we are getting similar results with using JAX .

#### Q6 Use sympy to confirm that you obtain the same gradient analytically.

In [10]:
import sympy as sp

x,y=sp.symbols('x y')
exp = x**2 * y + y**3 * sp.sin(x)
der_x = sp.diff(exp,x)
der_y = sp.diff(exp,y)
print((der_x))
print((der_y))

2*x*y + y**3*cos(x)
x**2 + 3*y**2*sin(x)


#### Q7 Create a Python nested dictionary to represent hierarchical information. We want to store record of students and their marks. Something like:

In [11]:
dict= {"2022":{"branch_1":{"Roll_No":101,"Name":'Harry',"Marks":{"Physics":100,"Maths":98}},

              "branch_2":{"Roll_No":102,"Name":'Rohan',"Marks":{"Chemistry":90,"English":99}}},

       "2023":{"branch_1":{"Roll_No":201,"Name":'Krishna',"Marks":{"Physics":100,"Maths":98}},

              "branch_2":{"Roll_No":202,"Name":'Hari',"Marks":{"Chemistry":85,"English":95}}},

       "2024":{"branch_1":{"Roll_No":301,"Name":'Mayank',"Marks":{"Physics":70,"Maths":28}},

              "branch_2":{"Roll_No":302,"Name":'Riyash',"Marks":{"Chemistry":92,"English":19}}},

       "2025":{"branch_1":{"Roll_No":401,"Name":'Ravi',"Marks":{"Physics":56,"Maths":48}},

              "branch_2":{"Roll_No":402,"Name":'Shivam',"Marks":{"Chemistry":60,"English":89}}}
           }

In [12]:
print(dict)

{'2022': {'branch_1': {'Roll_No': 101, 'Name': 'Harry', 'Marks': {'Physics': 100, 'Maths': 98}}, 'branch_2': {'Roll_No': 102, 'Name': 'Rohan', 'Marks': {'Chemistry': 90, 'English': 99}}}, '2023': {'branch_1': {'Roll_No': 201, 'Name': 'Krishna', 'Marks': {'Physics': 100, 'Maths': 98}}, 'branch_2': {'Roll_No': 202, 'Name': 'Hari', 'Marks': {'Chemistry': 85, 'English': 95}}}, '2024': {'branch_1': {'Roll_No': 301, 'Name': 'Mayank', 'Marks': {'Physics': 70, 'Maths': 28}}, 'branch_2': {'Roll_No': 302, 'Name': 'Riyash', 'Marks': {'Chemistry': 92, 'English': 19}}}, '2025': {'branch_1': {'Roll_No': 401, 'Name': 'Ravi', 'Marks': {'Physics': 56, 'Maths': 48}}, 'branch_2': {'Roll_No': 402, 'Name': 'Shivam', 'Marks': {'Chemistry': 60, 'English': 89}}}}


#### Q8 Store the same information using Python classes. We have an overall database which is a list of year objects. Each year contains a list of branches. Each branch contains a list of students. Each student has some properties like name, roll number and has marks in some subjects.

In [13]:
class Student:
    def __init__(self, year, branch, rollNo, name, **subjectWithMakrs):
        self.year = year
        self.branch = branch
        self.rollNo = rollNo
        self.name = name
        self.subjectWithMakrs = subjectWithMakrs

    def __str__(self):
        return f"Name: {self.name}, \nRoll No: {self.rollNo}, \nBranch: {self.branch}, \nYear: {self.year}, \nSubjects: {self.subjectWithMakrs}"

std1 = Student(2022, "Computer Science", 101, "Bunty", Maths=100, Physics=98)
std2 = Student(2023, "Computer Science", 102, "prince", Maths=99, Physics=97)

print(std1)
print(std2)


Name: Bunty, 
Roll No: 101, 
Branch: Computer Science, 
Year: 2022, 
Subjects: {'Maths': 100, 'Physics': 98}
Name: prince, 
Roll No: 102, 
Branch: Computer Science, 
Year: 2023, 
Subjects: {'Maths': 99, 'Physics': 97}


#### Q10 Using numpy generate a matrix of size 20X5 containing random numbers drawn uniformly from the range of 1 to 2. Using Pandas create a dataframe out of this matrix. Name the columns of the dataframe as “a”, “b”, “c”, “d”, “e”. Find the column with the highest standard deviation. Find the row with the lowest mean.

In [14]:
import pandas as pd


mat=np.random.uniform(1.0,2.0,(20,5))

print(mat)

df = pd.DataFrame(mat, columns=['a','b','c','d','e'])

print(df)

std_dev = np.std(mat, axis=0)
print(std_dev)



[[1.33774677 1.61001281 1.28254454 1.52205626 1.58595807]
 [1.69405745 1.48581907 1.16986781 1.88631472 1.16944686]
 [1.77563679 1.04215895 1.08842449 1.50606892 1.68435362]
 [1.04628695 1.89258746 1.07606887 1.76384638 1.50093818]
 [1.87747911 1.18715729 1.21505412 1.32357769 1.89771254]
 [1.06231634 1.37386635 1.71464497 1.21241574 1.06099586]
 [1.87573262 1.42895387 1.35161369 1.0123227  1.96782749]
 [1.29271141 1.40856975 1.70649972 1.32662077 1.10946673]
 [1.49194902 1.58325778 1.35818366 1.55398255 1.21460065]
 [1.66431513 1.25961888 1.13201585 1.02793012 1.7542249 ]
 [1.90265682 1.30089544 1.31404316 1.37163919 1.58762188]
 [1.16936008 1.85685568 1.35785805 1.76262216 1.12735261]
 [1.9416232  1.82951193 1.88320509 1.95915031 1.45982484]
 [1.25000392 1.40945565 1.05758307 1.40819682 1.85066422]
 [1.70816363 1.15128422 1.77789134 1.18596157 1.94661575]
 [1.0096103  1.37673813 1.4874037  1.26450331 1.52909091]
 [1.06897824 1.20522635 1.34581354 1.50300225 1.27482743]
 [1.93012566 1

#### Q11 Add a new column to the dataframe called “f” which is the sum of the columns “a”, “b”, “c”, “d”, “e”. Create another column called “g”. The value in the column “g” should be “LT8” if the value in the column “f” is less than 8 and “GT8” otherwise. Find the number of rows in the dataframe where the value in the column “g” is “LT8”. Find the standard deviation of the column “f” for the rows where the value in the column “g” is “LT8” and “GT8” respectively.


In [15]:
for index, row in df.iterrows():
    df.loc[index, 'f'] = sum(row)

print(df)

           a         b         c         d         e         f
0   1.337747  1.610013  1.282545  1.522056  1.585958  7.338318
1   1.694057  1.485819  1.169868  1.886315  1.169447  7.405506
2   1.775637  1.042159  1.088424  1.506069  1.684354  7.096643
3   1.046287  1.892587  1.076069  1.763846  1.500938  7.279728
4   1.877479  1.187157  1.215054  1.323578  1.897713  7.500981
5   1.062316  1.373866  1.714645  1.212416  1.060996  6.424239
6   1.875733  1.428954  1.351614  1.012323  1.967827  7.636450
7   1.292711  1.408570  1.706500  1.326621  1.109467  6.843868
8   1.491949  1.583258  1.358184  1.553983  1.214601  7.201974
9   1.664315  1.259619  1.132016  1.027930  1.754225  6.838105
10  1.902657  1.300895  1.314043  1.371639  1.587622  7.476856
11  1.169360  1.856856  1.357858  1.762622  1.127353  7.274049
12  1.941623  1.829512  1.883205  1.959150  1.459825  9.073315
13  1.250004  1.409456  1.057583  1.408197  1.850664  6.975904
14  1.708164  1.151284  1.777891  1.185962  1.946616  7

#### Q12 Write a small piece of code to explain broadcasting in numpy.

In [16]:
import numpy as np

# Create two arrays of different shapes
arr1 = np.array([1, 2, 3])
arr2 = np.array(5)

# Broadcasting: element-wise operation with smaller array stretched to match the larger
broadcasted_sum = arr1 + arr2

# Print the result
print(broadcasted_sum)  # Output: [6 7 8]

# Explanation:
# - arr2 (scalar 5) is stretched to match the shape of arr1 (3 elements)
# - During addition, each element of arr1 is added to the corresponding stretched element of arr2

# Another example:
arr3 = np.array([[1, 2], [3, 4]])
broadcasted_product = arr3 * arr2

# Print the result
print(broadcasted_product)  # Output: [[5 10], [15 20]]

# Explanation:
# - arr2 (scalar 5) is stretched to a 2x2 array with all elements equal to 5
# - Element-wise multiplication is performed between arr3 and the stretched arr2


[6 7 8]
[[ 5 10]
 [15 20]]


#### Q13 Write a function to compute the argmin of a numpy array. The function should take a numpy array as input and return the index of the minimum element. You can use the np.argmin function to verify your solution.

In [17]:
arr= np.random.randint(1,100,100)

import numpy as np

def custom_argmin(arr):
    min_value = arr[0]
    min_index = 0

    for i in range(1, len(arr)):
        if arr[i] < min_value:
            min_value = arr[i]
            min_index = i

    return min_index

result = custom_argmin(arr)

print("Custom argmin:", result)
print("NumPy argmin:", np.argmin(arr))



Custom argmin: 25
NumPy argmin: 25
